### ISSUE TITLE
Support nested selects

### ISSUE THREAD

**Issue by esentio** [esentio/Yamo#27]
Allow nested selects in joins and maybe on other places.

**Comment by esentio** [comment]
Current state of subquery support:

- [x] `FROM` table source (via #97)
- [x] `JOIN` table source (via #98)
- [x] `UNION`, `UNION ALL`, `EXCEPT` and `INTERSECT` set operators (via #99)
- [ ] `SELECT` clause expression
- [ ] `WHERE` clause expression (`IN`, `EXISTS`, ...)
